samples:
  sim-homo-0.0-100-60-0: bam/sim-homo-0.0-100-60-0.bam
  sim-homo-0.0-100-60-1: bam/sim-homo-0.0-100-60-1.bam
  sim-homo-0.0-1000-60-0: bam/sim-homo-0.0-1000-60-0.bam
  sim-homo-0.0-1000-60-1: bam/sim-homo-0.0-1000-60-1.bam
  sim-homo-0.96-100-60-0: bam/sim-homo-0.96-100-60-0.bam
  sim-homo-0.96-100-60-1: bam/sim-homo-0.96-100-60-1.bam
  sim-homo-0.96-1000-60-0: bam/sim-homo-0.96-1000-60-0.bam
  sim-homo-0.96-1000-60-1: bam/sim-homo-0.96-1000-60-1.bam
metaDMG_cpp: ./metaDMG-cpp
names: null
nodes: null
acc2tax: null
min_similarity_score: 0.95
max_similarity_score: 1.0
min_mapping_quality: 0
lca_rank: ''
max_position: 15
min_reads: 0
weight_type: 1
custom_database: false
forward_only: false
output_dir: data
parallel_samples: 10
cores_per_sample: 1
bayesian: true
config_file: config.yaml
damage_mode: local
version: 0.32.4
