samples:
  test: test.bam
metaDMG_cpp: ./metaDMG-cpp
names: null
nodes: null
acc2tax: null
min_similarity_score: 0.95
max_similarity_score: 1.0
min_mapping_quality: 0
lca_rank: ""
max_position: 15
min_reads: 0
weight_type: 1
custom_database: false
forward_only: false
output_dir: data-mini
parallel_samples: 1
cores_per_sample: 1
bayesian: false
config_file: config.yaml
damage_mode: local
version: 0.33.0
